### ISSUE TITLE
Guacamole default password?

### ISSUE THREAD

**Issue by Tharic99** [oznu/docker-guacamole#24]
Guacamole container installed from docker and when attempting to access the web url for the first time on port 8080, it asks for an Apache Guacamole username and password. Per the documentation I could find online, the default username would be "guacadmin" and "guacadmin" for the password, but this does not work.

To Reproduce
Install guacamole container and attempt to login.

Expected behavior
Default "guacadmin" and "guacadmin" username/password combo will work.

System (please complete the following information):

Ubuntu 18.04 running under docker

**Comment by nemchik** [comment]
I only have one user on my system, which is Ubuntu server 18.04. I chown'd to my one user (who's UID and GID are both `1000`). The container chowns things when it starts so the permissions are changed anyway, but only on certain folders it seems.

**Comment by Delvien** [comment]
I found what the problem is. If you have duo or any other extension that fiddles with login, you have to set that up first otherwise the default user name and password does not work.

**Comment by zenety** [comment]
Same here, started the container with extensions auth-totp and auth-duo. Default username and password did not work. Started it again without the extensions and the default information worked fine.

I then edited the container to add the auth. Tried to log-in with my newly created user and it got the error: Property duo-api-hostname is required.

**Comment by jmmille** [comment]
I had the same issue.  I restarted the container once after the initial build and was able to login fine with the default login.

**Comment by pozgo** [comment]
I agree restart seems to fix the login issue. Any idea what is this happening? Maybe we could send PR with fix if we know what it is/

**Comment by nemchik** [comment]
My first guess is permissions are set on start and then files are created with the wrong permissions after that. Restarting sets permissions on the files that were incorrect from the last run.

I'm not positive, just guessing.

**Comment by nemchik** [comment]
@whatsdis restart the container and try again.

**Comment by Madko** [comment]
same here, my config is on a convoy nfs volume. Haven't check the permission on this, but other containers work fine on this kind of volume.

**Comment by chrisbrownie** [comment]
Reboot worked for me as well. Docker on Ubuntu 18.04.1.

**Comment by mouazvd** [comment]
docker restart worked

**Comment by jcombs-pointblue** [comment]
I'm having the same issue using Docker on a mac. In the log I'm seeing:

LOG:  database system is ready to accept connections
FATAL:  role "root" does not exist
/var/run/postgresql:5432 - accepting connections

I assume the fatal error has something to with authN failing later. Any ideas?

**Comment by pozgo** [comment]
So far only restarting container fixes this issue.

**Comment by radium729** [comment]
I cannot log in either.  I am about to pull my hair out. I have spent days on this issue. it is so frustrating. I try to log in with default credentials, nothing happens it just blanks out what i type and stays on the login screen. It doesn't matter what i type nothing happens. I only receive a failed login in the logs if i type nothing in and try to login. I tried this on an existing linux docker install and a brand new install, both using 18.0.4. My friends install that i mirrored to a "T" works just fine. I restarted the server, container, deleted the image and the container, rebuilt the container, cloned the container, changed the permissions on everything in the config folder. Nothing works, no errors, starts up fine every time, just cant login.

**Comment by radium729** [comment]
I fixed it for now. I changed the port to a different one and i was able to login successfully.

**Comment by jcombs-pointblue** [comment]
Still not working for me. I've restarted and changed ports. Checked file permissions, DB files are there. Seeing no errors logged other than the "FATAL: role "root" does not exist

**Comment by radium729** [comment]
Jcombs, you might check your antivirus. I thought mine was a port issue but it ended up being bitdefender blocking me from entering my credentials in a non encrypted http site.i had to allow an exception in bitdefender to fix it. i only found out because i tried on a separate pc that didnt have bitdefender.

**Comment by Razva** [comment]
Worked only after `docker restart guacamole`. Any fix for newcommers?

**Comment by pozgo-qumu** [comment]
Is it closed because it's fixed or just no one wants to look into this? 😄 

> I fixed it for now. I changed the port to a different one and i was able to login successfully.

Did it get fixed on a different port? I don't see how that can be. If you used `docker-compose up` again with different port container got recreated but data was re-used so basically what it means is it got restarted 😄  Which is the usual "fix"
